### ISSUE TITLE
Metadata format

### ISSUE THREAD

**Issue by robinschmid** [michaelwitting/RepoRT#140]
Question about the metadata format - will it always be a single row?
This seems more like a yaml or json rather than a table.

Something like
```
id: 0259
column:
  id:
  name: Waters
  usp_code: L1
  length_mm: 100
  particle_size: 0.4
  temperature_c: 100
eluent:
  A:
    h2o: 100
    formic_acid: 0.1
  B:
    acn: 100
    formic_acid: 0.1

gradient:
  start:
    A: 95
    B: 5
  end:
    A: 0.5
    B: 99.5
```

https://media.githubusercontent.com/media/michaelwitting/RepoRT/master/example/0259_metadata.txt

Also, why are the start and end duplicated here?
They are also described in the gradient file right?

**Comment by f-kretschmer** [comment]
We are going to alternatively accept a YAML file for the metadata in the future, that really is so much better to read/adapt. The format will be something like the example below, so metadata fields will be for the most part identical between the tsv and yaml-version.

```yaml
id: 0259
column:
  name: Waters ACQUITY UPLC BEH C18
  usp.code: L1
  length: 100
  id: 2.1
  particle.size: 1.7
  temperature: 40
  flowrate: 0.4
eluent:
  A:
    h2o: 100
    formic:
      value: 0.1
      unit: '%'
  B:
    acn: 100
```
